[manifest]
type = "portable"
platform = "windows"
compat = "10^"

[app]
name = "Sumatra PDF Reader"

url = "https://www.sumatrapdfreader.org/download-free-pdf-viewer"
url-type = "page"
url-selector = ".page-wrap > table:nth-child(2) > tbody:nth-child(1) > tr:nth-child(3) > td:nth-child(2) > a:nth-child(1)"
url-version-selector = "(?<version>[0-9]+\\.[0-9]+\\.[0-9]+)"

decompress = true
filename = "SumatraPDF-{{version}}-64.exe"

[shortcuts]

[shortcuts.windows.start-menu]
name = "Sumatra PDF Reader"

[shortcuts.windows.desktop]
name = "Sumatra PDF Reader"
