# This is a basic workflow that is manually triggered

name: Compile Index

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    # Inputs the workflow accepts.
    branches: 'main'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  compile:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: compile file
      run: |
        python build_repo.py
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add -f './public/index.csv'
        git commit -m "Generated Index file on push"
        git push
